[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; camera 'self'; microphone 'none'"
    Feature-Policy = "camera 'self'"
    Permissions-Policy = "camera=(self), microphone=()"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"